"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {mirrorRecords} from "../../data";
import {allCodes,countryNames,latestByCountry,loadLivePrices,rowPrice,speciesLabel,type LivePriceRow} from "../../market-display";

const money=(value:number)=>value?`$${value.toLocaleString("en-US")}`:"暂无贸易额";
const readExpand=()=>typeof window==="undefined"?null:new URL(window.location.href).searchParams.get("expand")?.toUpperCase()??null;
export default function CountryAccordion(){const [expanded,setExpanded]=useState<string|null>(null);const [rows,setRows]=useState<LivePriceRow[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{setExpanded(readExpand());const pop=()=>setExpanded(readExpand());window.addEventListener("popstate",pop);loadLivePrices().then(setRows).finally(()=>setLoading(false));return()=>window.removeEventListener("popstate",pop)},[]);const latest=useMemo(()=>latestByCountry(rows),[rows]);const toggle=(code:string)=>{const next=expanded===code?null:code;setExpanded(next);const url=new URL(window.location.href);next?url.searchParams.set("expand",next):url.searchParams.delete("expand");window.history.pushState({},"",`${url.pathname}${url.search}`)};return <section className="country-accordion" aria-label="目标市场列表">{allCodes.map(code=>{const trade=mirrorRecords.filter(row=>row.countryCode===code);const total=trade.reduce((sum,row)=>sum+Number(row.importerCifUsd??row.confirmedTradeUsd??0),0);const prices=latest.filter(row=>row.country===code);const kg=prices.map(row=>row.normalized_usd_per_kg).filter((value):value is number=>value!=null);const channels=new Set(prices.map(row=>row.platform_name)).size;const date=prices.reduce((current,row)=>row.observation_date>current?row.observation_date:current,"");const open=expanded===code;return <article className={open?"open":""} key={code}><button type="button" onClick={()=>toggle(code)} aria-expanded={open}><span>{code}</span><b>{countryNames[code]}</b><em>{prices.length?`已有 ${prices.length} 条价格`:trade.length?"已有贸易数据":"市场信息"}</em><i aria-hidden="true">{open?"−":"＋"}</i></button><div className="country-inline-panel" aria-hidden={!open}><div><span>贸易额</span><strong>{trade.length?money(total):"价格市场"}</strong></div><div><span>主力品种价格</span><strong>{kg.length?`$${Math.min(...kg).toFixed(2)}–$${Math.max(...kg).toFixed(2)}/kg`:prices[0]?rowPrice(prices[0]):loading?"正在加载":"暂无公开价格"}</strong></div><div><span>渠道数</span><strong>{channels||"暂无渠道记录"}</strong></div><div><span>更新日期</span><strong>{date||"随贸易数据更新"}</strong></div><div><span>数据等级</span><strong>{trade[0]?.confidence??(prices.length?"B":"C")}</strong></div>{prices.length>0&&<p>{Array.from(new Set(prices.slice(0,3).map(row=>speciesLabel(row.species_id)))).join("、")}</p>}<Link prefetch href={`/markets/${code}#prices`}>查看完整国家详情 →</Link></div></article>})}</section>}
