import ProductShell from "../../product-shell";

type RoleKey="producer"|"channel"|"investor"|"researcher";
type RoleData={name:string;eyebrow:string;title:string;intro:string;priorities:string[];modules:{tag:string;title:string;copy:string;href:string;cta:string}[];products:{name:string;deliverable:string;fit:string;href:string}[]};
const roles:Record<RoleKey,RoleData>={
producer:{name:"产能方",eyebrow:"PRODUCER WORKSPACE",title:"从产能与品类出发，判断卖到哪里、卖什么价",intro:"围绕目标国价格、品类需求和进入路径，帮助菌菇生产企业筛选值得验证的市场。",priorities:["五国同品类价格比较","贸易规模与进口依赖","目标市场与合作对接"],modules:[{tag:"01 / 价格",title:"五国价格与价格洼地",copy:"比较同品类标准公斤价，识别高价市场，并保留规格与来源。",href:"/screen?role=产能方",cta:"打开产能方大屏"},{tag:"02 / 需求",title:"国别需求画像",copy:"查看进口金额、中国占比、零售价格区间及数据缺口。",href:"/insights",cta:"比较五国需求"},{tag:"03 / 路径",title:"出海机会验证",copy:"从已验证需求信号进入渠道、规格和合作条件核验。",href:"/expand/radar",cta:"查看商机雷达"}],products:[{name:"五国价格监测",deliverable:"日度价格摘要、SKU 来源、异常提示",fit:"适合制定出口报价与选品",href:"/market"},{name:"目标国进入研究",deliverable:"市场规模、品类结构、渠道与风险清单",fit:"适合确定首站市场",href:"/insights/country"},{name:"合作对接服务",deliverable:"需求梳理与潜在合作方向",fit:"适合已有产能和出口计划的企业",href:"/expand/contact"}]},
channel:{name:"渠道商",eyebrow:"CHANNEL WORKSPACE",title:"围绕 SKU、供给和价格，提升选品与采购效率",intro:"优先呈现商品明细、平台价差和市场新品，帮助进口商、经销商与零售渠道发现可采购品类。",priorities:["SKU 与规格明细","平台价差和新品扫描","供需匹配与合作对接"],modules:[{tag:"01 / SKU",title:"可追溯商品价格",copy:"按国家、菌种、形态和平台筛选商品，查看原币价格和来源页。",href:"/terminal",cta:"进入 SKU 终端"},{tag:"02 / 新品",title:"品类与新品扫描",copy:"查看市场中已出现的平菇、香菇等品类及有效记录数量。",href:"/market/scan",cta:"查看新品扫描"},{tag:"03 / 行情",title:"渠道价格摘要",copy:"快速比较今日有效公斤价和平台覆盖情况。",href:"/market",cta:"查看市场行情"}],products:[{name:"渠道价格看板",deliverable:"平台、规格、本币与美元标准价",fit:"适合采购比价和零售定价",href:"/screen?role=渠道商"},{name:"新品监测",deliverable:"新增菌种、产品形态与平台记录",fit:"适合扩充商品组合",href:"/market/scan"},{name:"采购合作对接",deliverable:"需求品类、规格和目标市场梳理",fit:"适合寻找供给和合作伙伴",href:"/expand/contact"}]},
investor:{name:"投资者",eyebrow:"INVESTOR WORKSPACE",title:"用贸易趋势与证据质量，验证市场结构和投资假设",intro:"突出贸易规模、品类趋势和数据可信度，不用缺失数据制造确定性。",priorities:["贸易规模与结构","增长趋势与风险","数据质量评级"],modules:[{tag:"01 / 规模",title:"五国贸易规模",copy:"按国家和 HS 品类查看 2024 已确认金额及来源口径。",href:"/insights/trade",cta:"查看贸易分析"},{tag:"02 / 评级",title:"数据质量与覆盖",copy:"同时呈现历史评级和今日价格缺口，避免覆盖数字自相矛盾。",href:"/screen?role=投资者",cta:"进入投资者大屏"},{tag:"03 / 机会",title:"机会与风险信号",copy:"查看有数据支持的需求信号、验证状态和下一步动作。",href:"/opportunities",cta:"查看机会清单"}],products:[{name:"中亚菌类投资简报",deliverable:"规模、趋势、结构与证据等级",fit:"适合投资初筛与内部讨论",href:"/reports"},{name:"国别专题研究",deliverable:"单国市场、供应链和风险框架",fit:"适合项目尽调前期",href:"/insights/country"},{name:"定制商业分析",deliverable:"围绕具体投资假设的数据核验",fit:"适合明确项目或赛道",href:"/expand/contact"}]},
researcher:{name:"研究者",eyebrow:"RESEARCH WORKSPACE",title:"进入全量视图，核验数据、口径、来源与方法",intro:"面向研究机构、高校和专业服务团队，提供数据终端、方法说明和可追溯报告入口。",priorities:["全量价格与贸易数据","来源、口径与可信度","报告与数据接口"],modules:[{tag:"01 / 数据",title:"全量数据终端",copy:"查看价格明细、贸易记录和数据资产，不把缺失值填为零。",href:"/screen?role=研究者",cta:"打开研究者大屏"},{tag:"02 / 方法",title:"来源与方法说明",copy:"了解分类、标准化、交叉核验和置信等级。",href:"/docs",cta:"查看方法文档"},{tag:"03 / 报告",title:"市场研究报告",copy:"阅读日报、周报、月报及专题研究。",href:"/reports",cta:"进入报告中心"}],products:[{name:"研究数据终端",deliverable:"价格、贸易、品类和来源字段",fit:"适合持续研究与数据核验",href:"/terminal"},{name:"数据资产目录",deliverable:"数据集范围、频率与字段说明",fit:"适合课题和模型选数",href:"/data-assets"},{name:"专题研究服务",deliverable:"可复核的数据整理与研究报告",fit:"适合机构课题与定制分析",href:"/expand/contact"}]}}

export function generateStaticParams(){return Object.keys(roles).map(role=>({role}))}
export async function generateMetadata({params}:{params:Promise<{role:string}>}){const {role}=await params;const item=roles[role as RoleKey];return {title:item?`${item.name}工作台｜中亚食用菌出海服务平台`:"角色工作台"}}
export default async function RolePage({params}:{params:Promise<{role:string}>}){const {role}=await params;const item=roles[role as RoleKey];if(!item)return <ProductShell><main className="saas-main"><section className="role-workspace-hero"><h1>角色页面不存在</h1><a href="/#roles">返回首页</a></section></main></ProductShell>;
return <ProductShell><main className="saas-main role-workspace"><section className="role-workspace-hero"><span>{item.eyebrow}</span><div><p>{item.name}专属市场服务</p><h1>{item.title}</h1><strong>{item.intro}</strong><div className="role-priority-row">{item.priorities.map(x=><b key={x}>{x}</b>)}</div></div><aside><span>MARKET ENTRY</span><p>从关键市场信息开始，快速了解当前行情、需求结构与可推进的业务方向。</p><a href={item.modules[0].href}>{item.modules[0].cta} →</a></aside></section><section className="role-workspace-head"><span>MARKET INTELLIGENCE</span><h2>{item.name}关注的核心市场信息</h2><p>围绕{item.priorities.join("、")}提供清晰、可追溯的市场参考。</p></section><section className="role-module-grid">{item.modules.map(module=><a href={module.href} key={module.title}><span>{module.tag}</span><h3>{module.title}</h3><p>{module.copy}</p><b>{module.cta} →</b></a>)}</section><section className="role-workspace-head"><span>PRODUCTS & SERVICES</span><h2>面向{item.name}的产品与服务</h2><p>按业务阶段选择数据产品、市场研究或合作对接服务。</p></section><section className="role-product-list">{item.products.map((product,i)=><article key={product.name}><span>0{i+1}</span><div><h3>{product.name}</h3><p>{product.deliverable}</p></div><small>{product.fit}</small><a href={product.href}>查看产品 →</a></article>)}</section><section className="role-workspace-cta"><div><span>BUSINESS CONSULTATION</span><h2>围绕目标国家、品类或项目开展合作</h2><p>提交您的业务目标，我们将结合现有市场信息与服务能力进一步沟通。</p></div><a href="/expand/contact">发起合作对接 →</a></section></main></ProductShell>}
