import { env } from "cloudflare:workers";

const median=(values:number[])=>{const x=[...values].sort((a,b)=>a-b),n=x.length;return n?n%2?x[(n-1)/2]:(x[n/2-1]+x[n/2])/2:null};
type Row={observation_date:string;country:string;city:string;species_id:string;product_form:string;currency:string;normalized_price_per_kg:number;regular_price:number|null;promotion_price:number|null;normalized_quantity_kg:number|null;in_stock:number|null;platform_id:string;collection_point_id:string;classification_confidence:number};

export async function POST(request:Request){
 if(!process.env.CRON_SECRET||request.headers.get("x-cron-secret")!==process.env.CRON_SECRET)return Response.json({error:"Unauthorized"},{status:401});
 const date=(await request.json().catch(()=>({})) as {date?:string}).date??new Date().toISOString().slice(0,10),db=(env as unknown as {DB:D1Database}).DB;
 const rows=(await db.prepare(`SELECT po.observation_date,p.country,p.city,p.species_id,p.product_form,po.currency,po.normalized_price_per_kg,po.regular_price,po.promotion_price,po.normalized_quantity_kg,po.in_stock,p.platform_id,p.collection_point_id,p.classification_confidence FROM price_observations po JOIN products p ON p.id=po.product_id WHERE po.observation_date=? AND po.validation_status='valid' AND p.classification_status='classified' AND p.classification_confidence>=0.90 AND p.product_form NOT IN ('prepared_food','unknown','mixed') AND po.normalized_price_per_kg IS NOT NULL`).bind(date).all<Row>()).results;
 const groups=new Map<string,Row[]>();for(const row of rows){const key=[row.observation_date,row.country,row.city,row.species_id,row.product_form,row.currency].join("|");groups.set(key,[...(groups.get(key)??[]),row])}
 let written=0;for(const [key,items] of groups){const [day,country,city,species,form,currency]=key.split("|"),prices=items.map(x=>x.normalized_price_per_kg),regular=items.filter(x=>x.regular_price!=null&&x.normalized_quantity_kg).map(x=>x.regular_price!/x.normalized_quantity_kg!),promo=items.filter(x=>x.promotion_price!=null&&x.normalized_quantity_kg).map(x=>x.promotion_price!/x.normalized_quantity_kg!),now=Date.now(),quality=items.length>=5?"A":items.length>=3?"B":"C";
  await db.prepare(`INSERT INTO daily_price_summaries(id,date,country,city,species_id,product_form,valid_sku_count,in_stock_sku_count,platform_count,store_count,min_price,median_price,max_price,average_price,regular_median_price,promotion_median_price,promotion_share,out_of_stock_rate,currency,quality_grade,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(date,country,city,species_id,product_form,currency) DO UPDATE SET valid_sku_count=excluded.valid_sku_count,in_stock_sku_count=excluded.in_stock_sku_count,platform_count=excluded.platform_count,store_count=excluded.store_count,min_price=excluded.min_price,median_price=excluded.median_price,max_price=excluded.max_price,average_price=excluded.average_price,regular_median_price=excluded.regular_median_price,promotion_median_price=excluded.promotion_median_price,promotion_share=excluded.promotion_share,out_of_stock_rate=excluded.out_of_stock_rate,quality_grade=excluded.quality_grade,updated_at=excluded.updated_at`).bind(key,day,country,city,species,form,items.length,items.filter(x=>x.in_stock!==0).length,new Set(items.map(x=>x.platform_id)).size,new Set(items.map(x=>x.collection_point_id)).size,Math.min(...prices),median(prices),Math.max(...prices),prices.reduce((a,b)=>a+b,0)/prices.length,median(regular),median(promo),items.filter(x=>x.promotion_price!=null).length/items.length,items.filter(x=>x.in_stock===0).length/items.length,currency,quality,now,now).run();written++}
 return Response.json({ok:true,date,sourceRows:rows.length,written});
}
