import { notFound } from "next/navigation";
import ProductShell from "../../product-shell";
import { mirrorRecords, opportunities, priceObservations } from "../../data";

const profiles={
  kz:{code:"KZ",name:"哈萨克斯坦",conclusion:"现有贸易规模在五国中领先，适合作为鲜品冷链与渠道成交条件的首要验证市场。",competition:"进口国申报显示市场来源多元；中国金额占比需按具体 HS 品类分别判断。",channel:"已观察到阿拉木图电商、商超、小批发和批发渠道，但挂牌价不等于成交价。",logistics:"喀什—阿拉木图冷链报价、时效、损耗和通关异常尚未形成连续样本。",access:"准入、标签、检疫和进口主体要求需按具体产品形态逐项复核。"},
  uz:{code:"UZ",name:"乌兹别克斯坦",conclusion:"市场规模较小但存在品类验证空间，适合从塔什干渠道和明确规格开始小范围测试。",competition:"现有进口申报可确认市场规模；鲜品来源国和中国份额证据仍不完整。",channel:"已接入塔什干部分电商与零售观察，批发成交和稳定供货关系仍需验证。",logistics:"喀什—塔什干线路报价、冷链损耗和到岸成本尚未形成可发布基准。",access:"准入、标签、检疫和本地经营要求需结合产品形态与进口主体核验。"},
} as const;

export default async function CountryPage({params}:{params:Promise<{code:string}>}){const {code}=await params;const profile=profiles[code.toLowerCase() as keyof typeof profiles];if(!profile)notFound();const rows=mirrorRecords.filter(x=>x.countryCode===profile.code);const prices=priceObservations.filter(x=>x.countryCode===profile.code);const opportunity=opportunities.find(x=>x.countryCode===profile.code);const total=rows.reduce((sum,x)=>sum+Number(x.importerCifUsd??x.confirmedTradeUsd??0),0);const china=rows.reduce((sum,x)=>sum+Number(x.chinaFobUsd??0),0);const share=total&&rows.some(x=>x.chinaFobUsd!=null)?china/total*100:null;return <ProductShell><main className="saas-main country-decision-page">
  <section className="saas-hero compact"><span>{profile.code} · MARKET ENTRY</span><h1>{profile.name}市场进入判断</h1><p>{profile.conclusion}</p><div className="country-evidence-meta"><b>{rows[0]?.confidence??"—"} 级证据</b><span>统计年度 2024</span><span>更新时间 2026-08-17</span></div></section>
  <section className="country-decision-kpis"><article><span>已确认贸易规模</span><strong>${total.toLocaleString("en-US")}</strong><small>HS 070951/200310，进口国申报口径</small></article><article><span>中国金额占比</span><strong>{share==null?"—":`${share.toFixed(1)}%`}</strong><small>中国来源金额 / 已确认进口金额</small></article><article><span>已确认品类</span><strong>{rows.length}</strong><small>{rows.map(x=>`HS ${x.hs}`).join("、")||"—"}</small></article></section>
  <section className="country-judgement-grid"><article><span>市场容量与趋势</span><h2>{opportunity?.product??"重点品类待确认"}</h2><p>{opportunity?.signal??"当前证据不足以形成趋势判断。"}</p></article><article><span>竞争来源与中国份额</span><h2>按 HS 品类分别核验</h2><p>{profile.competition}</p></article><article><span>主流品类与价格带</span><h2>{prices.length?`${prices.length} 组公开观察` : "最近有效价格待补充"}</h2><p>{prices.length?prices.map(x=>`${x.product}：${x.price}`).join("；"):"接口或来源缺失时不以零值代替。"}</p></article><article><span>渠道与供应结构</span><h2>从公开挂牌进入成交验证</h2><p>{profile.channel}</p></article><article><span>物流与到岸成本</span><h2>待真实线路报价验证</h2><p>{profile.logistics}</p></article><article><span>准入与经营风险</span><h2>按产品形态逐项核对</h2><p>{profile.access}</p></article></section>
  <section className="country-gaps"><div><span>EVIDENCE GAPS</span><h2>当前证据缺口与待验证问题</h2></div><ul><li>同规格周度成交价与采购量</li><li>稳定采购渠道及账期条件</li><li>冷链线路、损耗和到岸成本</li><li>产品标签、检疫与进口主体要求</li></ul></section>
  <section className="country-next"><div><span>NEXT ACTION</span><h2>{opportunity?.nextAction??"补充渠道、物流与准入证据"}</h2><p>建议先形成小范围验证任务，再决定报价、打样或扩大投入。</p></div><div><a href="/terminal">核验价格来源 →</a><a href="/expand/contact">申请市场验证 →</a></div></section>
  <section className="country-source-note"><b>来源与口径</b><p>贸易：UN Comtrade 2024 进口申报及伙伴国镜像；价格：公开市场挂牌观察；挂牌价不等于成交价。缺失维度明确保留为待验证。</p></section>
</main></ProductShell>}
