type R=[string,string,string,string,number,number|null,string,number|null,string,string,string,string,string,string];
// city, species, title, spec, low, high, currency, kg, platform, url, date, grade, type, notes
const rows:R[]=[
["万象","oyster_mushroom","ເຫັດນາງລົມ Oyster Mushroom / 平菇","100g",20000,null,"LAK",.1,"Champa Garden Shop","https://champagardenshop.com/products/white-mushroom","2026-04-30","A","正常","页面公开零售价"],
["万象","wood_ear","ເຫັດຈອກດຳ / 黑木耳","未标重量",18000,null,"LAK",null,"Champa Market / foodpanda","https://www.foodpanda.la/shop/s8f0/champa-market","2026-08-28","A","正常","foodpanda商品页未标重量"],
["万象","wood_ear","Wood Ear Mushroom / 木耳","1 plate",11000,null,"LAK",null,"MK Nakham / foodpanda","https://www.foodpanda.la/en/restaurant/ay2d/mk-restaurant-naakham-ay2d","2026-08-17","B","正常","餐饮渠道单盘配菜价"],
["万象","shiitake","Shitake Mushrooms / 香菇","1 plate",21000,null,"LAK",null,"MK Nakham / foodpanda","https://www.foodpanda.la/en/restaurant/ay2d/mk-restaurant-naakham-ay2d","2026-08-17","B","正常","餐饮渠道单盘配菜价"],
["万象","oyster_mushroom","King Oyster Mushrooms / 杏鲍菇","1 plate",12000,null,"LAK",null,"MK Nakham / foodpanda","https://www.foodpanda.la/en/restaurant/ay2d/mk-restaurant-naakham-ay2d","2026-08-17","B","正常","杏鲍菇餐饮配菜价"],
["万象","shiitake","C01 Shiitake Mushroom 香菇","1 pc",6768,7200,"LAK",null,"Ping Chin / foodpanda","https://www.foodpanda.la/en/restaurant/v6nz/chyyn-piingchiinpaaesin-chen-yi-zha-kao-v6nz/reviews","2026-08-31","B","促销","烧烤单串；原价7200"],
["万象","shiitake","C01 Shiitake Mushroom 香菇（原价）","1 pc",7200,null,"LAK",null,"Ping Chin / foodpanda","https://www.foodpanda.la/en/restaurant/v6nz/chyyn-piingchiinpaaesin-chen-yi-zha-kao-v6nz/reviews","2026-08-31","B","正常","同页促销价6768"],
["万象","wood_ear","C02 Wood Ear Mushroom 木耳","1 pc",4700,5000,"LAK",null,"Ping Chin / foodpanda","https://www.foodpanda.la/en/restaurant/v6nz/chyyn-piingchiinpaaesin-chen-yi-zha-kao-v6nz/reviews","2026-08-31","B","促销","烧烤单串；原价5000"],
["万象","wood_ear","C02 Wood Ear Mushroom 木耳（原价）","1 pc",5000,null,"LAK",null,"Ping Chin / foodpanda","https://www.foodpanda.la/en/restaurant/v6nz/chyyn-piingchiinpaaesin-chen-yi-zha-kao-v6nz/reviews","2026-08-31","B","正常","同页促销价4700"],
["万象","oyster_mushroom","C05 Oyster Mushroom 炸平菇","1 pc",7426,7900,"LAK",null,"Ping Chin / foodpanda","https://www.foodpanda.la/en/restaurant/v6nz/chyyn-piingchiinpaaesin-chen-yi-zha-kao-v6nz/reviews","2026-08-31","B","促销","烧烤单串；原价7900"],
["万象","oyster_mushroom","C05 Oyster Mushroom 炸平菇（原价）","1 pc",7900,null,"LAK",null,"Ping Chin / foodpanda","https://www.foodpanda.la/en/restaurant/v6nz/chyyn-piingchiinpaaesin-chen-yi-zha-kao-v6nz/reviews","2026-08-31","B","正常","同页促销价7426"],
["琅勃拉邦","shiitake","Shiitake Mushroom / 香菇烤串","1 pc",4000,5000,"LAK",null,"Ping Jeen Zap / foodpanda","https://www.foodpanda.la/en/restaurant/y82m/aanpiingchiineisbwiailechoaaekoaa-3-7-9/reviews","2026-08-31","B","促销","原价5000"],
["琅勃拉邦","shiitake","Shiitake Mushroom / 香菇烤串（原价）","1 pc",5000,null,"LAK",null,"Ping Jeen Zap / foodpanda","https://www.foodpanda.la/en/restaurant/y82m/aanpiingchiineisbwiailechoaaekoaa-3-7-9/reviews","2026-08-31","B","正常","同页促销价4000"],
["琅勃拉邦","oyster_mushroom","Eringi Mushroom / 杏鲍菇烤串","1 pc",4000,5000,"LAK",null,"Ping Jeen Zap / foodpanda","https://www.foodpanda.la/en/restaurant/y82m/aanpiingchiineisbwiailechoaaekoaa-3-7-9/reviews","2026-08-31","B","促销","页面描述为oyster mushroom；原价5000"],
["琅勃拉邦","oyster_mushroom","Eringi Mushroom / 杏鲍菇烤串（原价）","1 pc",5000,null,"LAK",null,"Ping Jeen Zap / foodpanda","https://www.foodpanda.la/en/restaurant/y82m/aanpiingchiineisbwiailechoaaekoaa-3-7-9/reviews","2026-08-31","B","正常","同页促销价4000"],
["万象","wood_ear","Yum Wood Ear Mushroom / 凉拌木耳","1 plate",96900,114000,"LAK",null,"12 Phanna / foodpanda","https://www.foodpanda.la/en/restaurant/wkd5/aan-aahaan-12-phnnaa-wkd5","2026-08-30","B","促销","原价114000"],
["万象","wood_ear","Yum Wood Ear Mushroom / 凉拌木耳（原价）","1 plate",114000,null,"LAK",null,"12 Phanna / foodpanda","https://www.foodpanda.la/en/restaurant/wkd5/aan-aahaan-12-phnnaa-wkd5","2026-08-30","B","正常","同页促销价96900"],
["老挝全国","oyster_mushroom","Oyster mushrooms / 平菇","1kg",4,null,"USD",1,"Explore Laos","https://explore-laos.com/mushrooms-for-the-masses/","2020-05-01","C","历史基准","老挝平菇稳定价格约4美元/kg"],
["老挝全国","oyster_mushroom","Oyster mushroom farm-gate / 平菇农场价（待核）","1kg",70000,null,"LAK",1,"Pha Khao Lao","https://phakhaolao.la/wp-content/uploads/2024/09/mushroom-brochure_final.pdf","2024-09-01","C","历史基准","摘要显示农场价最高70000kip；品种待核"],
["越南供给锚","shiitake","Contracted shiitake / 香菇合同价","1kg",70000,null,"VND",1,"JICA Vietnam","https://daln.gov.vn/image_static/ms_sid_60/ms44/7072/ms44707277727570/ms44707277727570.pdf","2021-01-01","C","历史基准","越南供给锚"],
["泰国供给锚","shiitake","Fresh Shiitake / 鲜香菇","1kg",230,null,"THB",1,"Delish Foods Thailand","https://anyflip.com/mucxl/arwt/basic","2024-06-01","C","历史基准","泰国批发供给锚"],
["泰国供给锚","oyster_mushroom","Oyster Mushroom / 平菇","1kg",308,null,"THB",1,"Delish Foods Thailand","https://anyflip.com/mucxl/arwt/basic","2024-06-01","C","历史基准","泰国批发供给锚"],
["泰国供给锚","wood_ear","Cloud Ears Mushroom / 黑木耳","1kg",177,null,"THB",1,"Delish Foods Thailand","https://anyflip.com/mucxl/arwt/basic","2024-06-01","C","历史基准","泰国批发供给锚"],
["泰国供给锚","shiitake","Dried Shiitake / 干香菇","1kg",490,null,"THB",1,"Delish Foods Thailand","https://anyflip.com/mucxl/arwt/basic","2024-06-01","C","历史基准","泰国批发供给锚"],
...[["Bulk Dried Kikurage",2.1,"500kg MOQ"],["White Back Black Fungus",3,"区间$3–5"],["Vietnamese Wood-Ear Dried",2,"区间$2–8"],["Wood Ear Fungus",2.7,"区间$2.7–4"],["Premium Dried Black Fungus",1.5,"区间$1.5–3"],["Wholesale Dried Black Wood Ear",7,"区间$7–10.10"],["Cultivated Dried Black Fungus",2.09,"区间$2.09–4.19"],["Restaurant Supply Wood Ear",4.21,"区间$4.21–6.10"],["Top Grade Dried Wood Ear",4.5,"区间$4.5–8.5"],["Dried Black Fungus Strips",1.5,"区间$1.5–3"],["Frozen Raw Black Fungus",3.5,"区间$3.5–4.5"],["Sun-Dried Raw Wood Ear",4,"区间$4–8"],["Vietnam Wood Ear Mushroom",3.5,"500kg MOQ"],["Bulk Whole Wood Ear",4,"区间$4–5.5"]].map(([t,p,n])=>["越南供给锚","wood_ear",`${t} / 越南木耳`,"1kg",Number(p),null,"USD",1,"Alibaba Vietnam suppliers","https://www.alibaba.com/countrysearch/VN/wood-ear-mushroom.html","2026-06-30","C","区间",`越南批发供给锚；${n}`] as R),
["越南供给锚","wood_ear","Wholesale Black Fungus / 越南干木耳","1kg；MOQ 5000kg",2.7,null,"USD",1,"TradeKorea SAFIMEX","https://www.tradekorea.com/product/detail/P824880","2026-07-31","C","正常","越南FOB批发供给锚"],
["越南供给锚","wood_ear","Dried Woodear export / 越南干木耳出口价","1kg",2.5,11.4,"USD",1,"Tridge Vietnam","https://dir.tridge.com/prices/dried-woodear-mushroom/VN","2024-12-31","C","区间","2024出口价$2.50–11.40/kg"],
["越南供给锚","wood_ear","Dried Woodear import / 越南干木耳进口价","1kg",1.3,4.8,"USD",1,"Tridge Vietnam","https://dir.tridge.com/prices/dried-woodear-mushroom/VN","2024-12-31","C","区间","2024进口价$1.30–4.80/kg"]
];
const rate:Record<string,number>={LAK:22487.699349,VND:26073.33318,THB:33.159447,USD:1};
const safe=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"").slice(0,30);
export async function ensureLaosRawPriceIntel(db:D1Database){
 const old=await db.prepare("SELECT COUNT(*) n FROM products WHERE platform_product_id LIKE 'la_raw_%'").first<{n:number}>();
 if(Number(old?.n??0)>=rows.length)return {written:0,total:rows.length};
 const now=Date.now(),q:D1PreparedStatement[]=[];
 rows.forEach((x,i)=>{const [city,species,title,spec,low,high,currency,kg,name,url,date,grade,type,notes]=x,idx=String(i+1).padStart(3,"0"),platform=`raw_${safe(name)}_${idx}`,point=`la_raw_point_${idx}`,sku=`la_raw_${idx}`,product=`${platform}:${point}:${sku}`,fx=rate[currency]??1,perkg=kg?low/kg:null,evidence=JSON.stringify({grade,price_type:type,notes,spec,high_price:high,raw_pool:true});
 q.push(
 db.prepare("INSERT INTO species(id,name_zh,name_en,dictionary_version,review_status) VALUES(?,?,?,?,?) ON CONFLICT(id) DO NOTHING").bind(species,species,species,"raw-v1","raw"),
 db.prepare("INSERT INTO platforms(id,name,country,collection_method,status,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET updated_at=excluded.updated_at").bind(platform,name,"LA","raw_intelligence_pool","active",now),
 db.prepare("INSERT INTO collection_points(id,country,city,platform_id,timezone,active,public_label) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET active=1").bind(point,"LA",city,platform,"Asia/Vientiane",1,city),
 db.prepare("INSERT INTO products(id,platform_id,platform_product_id,collection_point_id,country,city,product_url,original_title,original_description,original_category,species_id,product_form,classification_status,classification_confidence,classification_evidence,first_seen_at,last_seen_at,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(platform_id,collection_point_id,platform_product_id) DO UPDATE SET original_title=excluded.original_title,classification_evidence=excluded.classification_evidence,last_seen_at=excluded.last_seen_at").bind(product,platform,sku,point,"LA",city,url,title,notes,"食用菌",species,type==="历史基准"?"historical":type==="区间"?"wholesale":spec.includes("plate")||spec.includes("pc")?"prepared_food":"fresh","classified",grade==="A"?.95:grade==="B"?.8:.6,evidence,now,now,1),
 db.prepare("INSERT INTO price_observations(id,product_id,observed_at,observation_date,current_price,regular_price,currency,package_value,package_unit,normalized_quantity_kg,normalized_price_per_kg,price_usd,usd_rate_local_per_usd,fx_source,in_stock,raw_price_text,source_url,source_type,collection_status,validation_status,validation_errors,sanity_outlier,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(product_id,observation_date) DO UPDATE SET current_price=excluded.current_price,regular_price=excluded.regular_price,raw_price_text=excluded.raw_price_text,validation_errors=excluded.validation_errors").bind(`${sku}:${date}`,product,new Date(`${date}T12:00:00+07:00`).getTime(),date,low,high,currency,kg,spec,kg,perkg,low/fx,fx,"任务采集参考汇率",1,high?`${low}–${high} ${currency}`:`${low} ${currency}`,url,"raw_price_intelligence","collected","valid",evidence,0,now));});
 let written=0,failed=0;for(let i=0;i<q.length;i+=5){try{await db.batch(q.slice(i,i+5));written++;}catch{failed++;}}return {written,failed,total:rows.length};
}
