"use client";
import {useEffect,useMemo,useState} from "react";
type Data={product_key?:string;species_id?:string;product_form?:string;product_shape?:string;processing_state?:string;packaging_type?:string;brand?:string|null;origin_country?:string|null;original_title?:string;package_display?:string;platform_name?:string;price_local?:number;regular_price_local?:number;currency?:string;price_usd?:number;normalized_price_usd_per_kg?:number|null;observed_at?:string;source_url?:string;source_type?:string;grade?:"A"|"B"|"C";notes?:string;status?:"live"|"gap"};
type Row={id:string;country:string;data:Data;source:string};
const countries:Record<string,string>={KZ:"哈萨克斯坦",UZ:"乌兹别克斯坦",KG:"吉尔吉斯斯坦",TJ:"塔吉克斯坦",TM:"土库曼斯坦",LA:"老挝",VN:"越南",TH:"泰国",MM:"缅甸",KH:"柬埔寨"};
const speciesMap:Record<string,string>={button_mushroom:"双孢菇",oyster_mushroom:"平菇",shiitake:"香菇",enoki:"金针菇",king_oyster_mushroom:"杏鲍菇",morel:"羊肚菌",porcini:"牛肝菌",chanterelle:"鸡油菌",honey_fungus:"蜜环菌",suillus:"乳牛肝菌",saffron_milk_cap:"松乳菌",milk_mushroom:"乳菇",blewit:"蓝柄菇",steppe_mushroom:"阿魏菇",shimeji:"真姬菇",wood_ear:"木耳",snow_fungus:"银耳",mixed_mushroom:"杂菌",unspecified_mushroom:"未标明菌种"};
const states:Record<string,string>={fresh:"鲜品",frozen:"冷冻",dried:"干品",pickled:"腌制",canned:"罐藏",prepared_food:"调理",powder:"粉末",chilled:"冷藏"},shapes:Record<string,string>={whole:"整粒",sliced:"切片",mixed:"混合",unspecified:"未标明"},packs:Record<string,string>={bulk:"散装/称重",packaged:"定量包装",portion:"按份/按串",unspecified:"未标明"};
const sources:Record<string,string>={"arbuz-kz":"Arbuz",globus:"Globus",omarket:"O!Market","lochin-uz":"Lochin","yukber-uz":"Yukber","magnit-tj":"Magnit",somon:"Somon",gipertm:"Giper",asmanexpress:"Asman"};
const fallback:Row[]=[{id:"kg-1",country:"KG",source:"globus",data:{species_id:"button_mushroom",product_form:"fresh",product_shape:"whole",processing_state:"fresh",packaging_type:"bulk",package_display:"1 kg",price_local:520,currency:"KGS",price_usd:5.95,normalized_price_usd_per_kg:5.95,observed_at:"2026-08-11",source_url:"https://globus-online.kg/",status:"live"}}];
const species=(d:Data)=>speciesMap[d.species_id??""]??"其他菌菇",money=(v:number)=>new Intl.NumberFormat("zh-CN",{maximumFractionDigits:2}).format(v);
const complete=(r:Row)=>r.data.status!=="gap"&&r.data.price_local!=null&&Boolean(r.data.currency&&r.data.observed_at&&r.data.package_display&&species(r.data)!=="其他菌菇");
const latestProducts=(records:Row[])=>Array.from(records.reduce((map,row)=>{
 const key=row.data.product_key??`${row.country}|${row.source}|${row.data.original_title??row.id}|${row.data.package_display??""}`;
 const current=map.get(key);
 if(!current||String(row.data.observed_at??"")>String(current.data.observed_at??""))map.set(key,row);
 return map;
},new Map<string,Row>()).values());
export default function PriceLiveTable(){
 const [rows,setRows]=useState<Row[]>(fallback),[country,setCountry]=useState("ALL"),[variety,setVariety]=useState("ALL"),[state,setState]=useState("ALL"),[pack,setPack]=useState("ALL"),[fallbackMode,setFallbackMode]=useState(true),[currency,setCurrency]=useState<"USD"|"CNY">("USD"),[cny,setCny]=useState<number|null>(null);
 useEffect(()=>{fetch("/api/ingest/snapshot?metric=price_retail&latest=1&limit=500").then(r=>r.ok?r.json() as Promise<{records?:Row[]}>:Promise.reject()).then(p=>{const v=latestProducts((p.records??[]).filter(complete));if(v.length){setRows(v);setFallbackMode(false)}}).catch(()=>{})},[]);
 useEffect(()=>{fetch("https://api.frankfurter.dev/v2/rate/USD/CNY").then(r=>r.ok?r.json() as Promise<{rate:number}>:Promise.reject()).then(p=>Number.isFinite(p.rate)&&setCny(p.rate)).catch(()=>{})},[]);
 const varieties=useMemo(()=>Array.from(new Set(rows.map(r=>species(r.data))).values()).sort(),[rows]);
 const visible=useMemo(()=>rows.filter(r=>(country==="ALL"||r.country===country)&&(variety==="ALL"||species(r.data)===variety)&&(state==="ALL"||(r.data.processing_state??r.data.product_form)===state)&&(pack==="ALL"||r.data.packaging_type===pack)).sort((a,b)=>[a.country,species(a.data),a.data.product_shape,a.data.processing_state,a.data.packaging_type].join("|").localeCompare([b.country,species(b.data),b.data.product_shape,b.data.processing_state,b.data.packaging_type].join("|"))),[rows,country,variety,state,pack]);
 return <><div className="live-price-filters"><label>国家<select value={country} onChange={e=>setCountry(e.target.value)}><option value="ALL">全部国家</option>{Object.entries(countries).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>菌种<select value={variety} onChange={e=>setVariety(e.target.value)}><option value="ALL">全部菌种</option>{varieties.map(v=><option key={v}>{v}</option>)}</select></label><label>处理状态<select value={state} onChange={e=>setState(e.target.value)}><option value="ALL">全部</option>{Object.entries(states).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>包装<select value={pack} onChange={e=>setPack(e.target.value)}><option value="ALL">全部</option>{Object.entries(packs).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><div className="currency-switch"><button className={currency==="USD"?"active":""} onClick={()=>setCurrency("USD")}>USD</button><button className={currency==="CNY"?"active":""} disabled={cny==null} onClick={()=>setCurrency("CNY")}>CNY</button></div><small>{fallbackMode?"已确认公开价格":`当前 ${visible.length} 个商品价格`}</small></div>
 <div className="live-price-table"><div className="live-price-row head"><b>国家</b><b>菌种</b><b>商品形态</b><b>处理状态</b><b>包装方式</b><b>品牌/产地</b><b>规格</b><b>渠道</b><b>当地价</b><b>{currency}/kg</b><b>日期</b><b>证据</b></div>{visible.map(r=>{const d=r.data,factor=currency==="CNY"?cny:1,unit=d.normalized_price_usd_per_kg!=null&&factor!=null?d.normalized_price_usd_per_kg*factor:null;return <div className="live-price-row" key={r.id} title={[d.original_title,d.source_type,d.grade&&`等级 ${d.grade}`,d.notes].filter(Boolean).join("｜")}><span>{countries[r.country]}</span><span>{species(d)}</span><span>{shapes[d.product_shape??""]??"未标明"}</span><span>{states[d.processing_state??d.product_form??""]??"未标明"}</span><span>{packs[d.packaging_type??""]??"未标明"}</span><span>{[d.brand,d.origin_country].filter(Boolean).join(" / ")||"未披露"}</span><span>{d.package_display}</span><span>{sources[r.source]??d.platform_name??r.source}{d.grade?` · ${d.grade}`:""}</span><span>{money(d.price_local!)} {d.currency}</span><span>{unit==null?"未折算":`${currency==="CNY"?"¥":"$"}${money(unit)}/kg`}</span><span>{d.observed_at}</span><span>{d.source_url?<a href={d.source_url} target="_blank" rel="noreferrer">来源 ↗</a>:"—"}</span></div>})}</div></>;
}
