"use client";
import { useEffect,useMemo,useState } from "react";

type PriceRecord={price:{observationDate:string;currentPrice:number|null;regularPrice:number|null;promotionPrice:number|null;currency:string;packageValue:number|null;packageUnit:string|null;normalizedPricePerKg:number|null;priceUsd:number|null;inStock:boolean|null;observedAt:string|number;validationStatus:string;sourceUrl:string};product:{id:string;country:string;city:string;originalTitle:string;speciesId:string|null;productForm:string;classificationConfidence:number;classificationStatus:string};platform:{id:string;name:string}};
const countryNames:Record<string,string>={KZ:"哈萨克斯坦",UZ:"乌兹别克斯坦",KG:"吉尔吉斯斯坦",TJ:"塔吉克斯坦",TM:"土库曼斯坦"};
const speciesNames:Record<string,string>={agaricus_bisporus:"双孢菇",pleurotus_ostreatus:"平菇",flammulina_velutipes:"金针菇",lentinula_edodes:"香菇",pleurotus_eryngii:"杏鲍菇",mixed_species:"混合菌菇",unknown_species:"未识别"};
const formNames:Record<string,string>={fresh:"鲜品",chilled:"冷藏",frozen:"冷冻",dried:"干制",pickled:"腌制",canned:"罐藏",powder:"菌粉",mixed:"混合",unknown:"未知"};
const fmt=(n:number|null,d=2)=>n==null?"—":n.toLocaleString("zh-CN",{maximumFractionDigits:d});
export default function MarketPanel({onState}:{onState:(state:"loading"|"live"|"fallback")=>void}){
 const [records,setRecords]=useState<PriceRecord[]>([]),[loading,setLoading]=useState(true),[country,setCountry]=useState("ALL"),[city,setCity]=useState("ALL"),[species,setSpecies]=useState("ALL"),[form,setForm]=useState("ALL"),[platform,setPlatform]=useState("ALL");
 useEffect(()=>{let active=true;const load=()=>fetch(`/api/prices?ts=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()).then((p:{records?:PriceRecord[]})=>{if(!active)return;setRecords(p.records??[]);onState(p.records?.length?"live":"fallback")}).catch(()=>onState("fallback")).finally(()=>setLoading(false));load();const timer=setInterval(load,30000);return()=>{active=false;clearInterval(timer)}},[onState]);
 const options=(key:"city"|"species"|"form"|"platform")=>[...new Set(records.map(r=>key==="city"?r.product.city:key==="species"?r.product.speciesId??"unknown_species":key==="form"?r.product.productForm:r.platform.id))];
 const filtered=useMemo(()=>records.filter(r=>(country==="ALL"||r.product.country===country)&&(city==="ALL"||r.product.city===city)&&(species==="ALL"||r.product.speciesId===species)&&(form==="ALL"||r.product.productForm===form)&&(platform==="ALL"||r.platform.id===platform)),[records,country,city,species,form,platform]);
 const normalized=filtered.map(r=>r.price.normalizedPricePerKg).filter((x):x is number=>x!=null).sort((a,b)=>a-b),median=normalized.length?normalized[Math.floor(normalized.length/2)]:null;
 return <><section className="intel-hero terminal-controls"><div><span>DAILY EDIBLE MUSHROOM PRICES</span><h1>中亚五国每日食用菌细分品类价格终端</h1><p>仅展示可追溯的在线零售商品观察价。原币、规格、每公斤标准价、美元折算与来源页面同步保留；缺失值不填零。</p></div><div className="asset-summary"><strong>{filtered.length}</strong><span>当前有效观察</span><strong>{new Set(filtered.map(r=>r.platform.id)).size}</strong><span>覆盖平台</span></div></section>
 <section className="live-price-filters terminal-price-filters"><label>国家<select value={country} onChange={e=>{setCountry(e.target.value);setCity("ALL")}}><option value="ALL">全部国家</option>{Object.entries(countryNames).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>城市<select value={city} onChange={e=>setCity(e.target.value)}><option value="ALL">全部城市</option>{options("city").map(v=><option key={v}>{v}</option>)}</select></label><label>菌种<select value={species} onChange={e=>setSpecies(e.target.value)}><option value="ALL">全部菌种</option>{options("species").map(v=><option value={v} key={v}>{speciesNames[v]??v}</option>)}</select></label><label>形态<select value={form} onChange={e=>setForm(e.target.value)}><option value="ALL">全部形态</option>{options("form").map(v=><option value={v} key={v}>{formNames[v]??v}</option>)}</select></label><label>平台<select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="ALL">全部平台</option>{options("platform").map(v=><option value={v} key={v}>{records.find(r=>r.platform.id===v)?.platform.name??v}</option>)}</select></label></section>
 <section className="intel-kpis"><article><span>最低标准价</span><strong>{normalized.length?`${fmt(normalized[0])} /kg`:"—"}</strong><small>原币口径，筛选内币种需一致</small></article><article><span>中位标准价</span><strong>{median==null?"—":`${fmt(median)} /kg`}</strong><small>仅可靠重量规格</small></article><article><span>最高标准价</span><strong>{normalized.length?`${fmt(normalized.at(-1)!)} /kg`:"—"}</strong><small>异常记录不静默汇总</small></article><article><span>待复核</span><strong>{filtered.filter(r=>r.price.validationStatus!=="valid"||r.product.classificationStatus!=="classified").length}</strong><small>分类或规格置信度不足</small></article></section>
 <section className="intel-table-panel"><div className="intel-panel-head"><div><span>TRACEABLE SKU OBSERVATIONS</span><h2>每日 SKU 明细</h2></div><small>页面观察价 · 非成交价</small></div><div className="intel-table"><div className="intel-row sku-price-row head"><span>日期 / 市场</span><span>商品 / 分类</span><span>平台 / 规格</span><span>原币 / 标准价</span><span>美元 / 状态</span><span>来源</span></div>{filtered.map(r=><div className="intel-row sku-price-row" key={`${r.product.id}-${r.price.observationDate}`}><span><b>{r.price.observationDate}</b><small>{countryNames[r.product.country]} · {r.product.city}</small></span><span><b>{r.product.originalTitle}</b><small>{speciesNames[r.product.speciesId??"unknown_species"]??r.product.speciesId} · {formNames[r.product.productForm]??r.product.productForm} · {(r.product.classificationConfidence*100).toFixed(0)}%</small></span><span><b>{r.platform.name}</b><small>{r.price.packageValue??"—"} {r.price.packageUnit??""}</small></span><span><b>{fmt(r.price.promotionPrice??r.price.currentPrice)} {r.price.currency}</b><small>{r.price.normalizedPricePerKg==null?"每公斤价待复核":`${fmt(r.price.normalizedPricePerKg)} ${r.price.currency}/kg`}</small></span><span><b>{r.price.priceUsd==null?"—":`$${fmt(r.price.priceUsd)}`}</b><small>{r.price.inStock===false?"缺货":r.price.validationStatus==="valid"?"有效":"待复核"}</small></span><span><a href={r.price.sourceUrl} target="_blank" rel="noreferrer">商品页 ↗</a></span></div>)}{!loading&&!filtered.length&&<div className="daily-empty"><strong>尚无符合条件的正式价格记录</strong><p>首次标准化采集正在运行。这里不会使用静态样例冒充实时数据，也不会把采集缺口解释为市场不存在该商品。</p></div>}{loading&&<div className="daily-empty"><strong>正在读取正式价格库…</strong></div>}</div></section></>;
}
